// Writes the production environment from API_URL at build time (Vercel sets it in the project settings).
import { writeFileSync } from 'node:fs';

const apiUrl = process.env.API_URL;
if (!apiUrl || !/^https:\/\//.test(apiUrl)) {
  console.error('API_URL must be set to the API base URL, e.g. https://ai-claims-api.onrender.com');
  process.exit(1);
}
writeFileSync(
  new URL('../src/environments/environment.production.ts', import.meta.url),
  `// Generated by scripts/write-env.mjs at build time. Do not edit.\n` +
    `export const environment = { production: true, apiUrl: '${apiUrl.replace(/\/$/, '')}' };\n`,
);
console.log(`environment.production.ts -> ${apiUrl}`);
